"""services/legend_data.py — Hardcoded legend F1 driver card definitions for Hall of Fame"""

LEGENDS = [
    {
        "id": "kimi",
        "name": "Kimi Räikkönen",
        "full_name": "Kimi Matias Räikkönen",
        "nationality": "Finland",
        "flag": "🇫🇮",
        "era": "2001–2021",
        "teams": ["Ferrari", "McLaren", "Lotus", "Alfa Romeo"],
        "championships": 1,
        "championship_years": [2007],
        "wins": 21,
        "poles": 18,
        "podiums": 46,
        "fastest_laps": 46,
        "quote": "Leave me alone, I know what I'm doing.",
        "color_primary": "#c0392b",
        "color_secondary": "#8e0000",
        "accent": "#e74c3c",
        "unlock_bets": 25,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #c0392b 0%, #8e0000 100%)",
    },
    {
        "id": "button",
        "name": "Jenson Button",
        "full_name": "Jenson Alexander Lyons Button",
        "nationality": "Britain",
        "flag": "🇬🇧",
        "era": "2000–2017",
        "teams": ["Brawn GP", "McLaren", "Williams", "BAR"],
        "championships": 1,
        "championship_years": [2009],
        "wins": 15,
        "poles": 8,
        "podiums": 50,
        "fastest_laps": 8,
        "quote": "The most important thing I've ever done.",
        "color_primary": "#2ecc71",
        "color_secondary": "#145a32",
        "accent": "#27ae60",
        "unlock_bets": 50,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #2ecc71 0%, #145a32 100%)",
    },
    {
        "id": "lauda",
        "name": "Niki Lauda",
        "full_name": "Andreas Nikolaus Lauda",
        "nationality": "Austria",
        "flag": "🇦🇹",
        "era": "1971–1985",
        "teams": ["Ferrari", "McLaren", "Brabham", "BRM"],
        "championships": 3,
        "championship_years": [1975, 1977, 1984],
        "wins": 25,
        "poles": 24,
        "podiums": 54,
        "fastest_laps": 25,
        "quote": "If you no longer go for a gap, you are no longer a racing driver.",
        "color_primary": "#e67e22",
        "color_secondary": "#784212",
        "accent": "#f39c12",
        "unlock_bets": 80,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #e67e22 0%, #784212 100%)",
    },
    {
        "id": "mansell",
        "name": "Nigel Mansell",
        "full_name": "Nigel Ernest James Mansell",
        "nationality": "Britain",
        "flag": "🇬🇧",
        "era": "1980–1995",
        "teams": ["Williams", "Ferrari", "Newman/Haas"],
        "championships": 1,
        "championship_years": [1992],
        "wins": 31,
        "poles": 32,
        "podiums": 59,
        "fastest_laps": 30,
        "quote": "Il Leone — The Lion",
        "color_primary": "#8e44ad",
        "color_secondary": "#4a235a",
        "accent": "#9b59b6",
        "unlock_bets": 120,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #8e44ad 0%, #4a235a 100%)",
    },
    {
        "id": "hill_d",
        "name": "Damon Hill",
        "full_name": "Damon Graham Devereux Hill",
        "nationality": "Britain",
        "flag": "🇬🇧",
        "era": "1992–1999",
        "teams": ["Williams", "Arrows", "Jordan"],
        "championships": 1,
        "championship_years": [1996],
        "wins": 22,
        "poles": 20,
        "podiums": 42,
        "fastest_laps": 19,
        "quote": "Son of a champion, champion.",
        "color_primary": "#1abc9c",
        "color_secondary": "#0e6655",
        "accent": "#16a085",
        "unlock_bets": 150,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #1abc9c 0%, #0e6655 100%)",
    },
    {
        "id": "prost",
        "name": "Alain Prost",
        "full_name": "Alain Marie Pascal Prost",
        "nationality": "France",
        "flag": "🇫🇷",
        "era": "1980–1993",
        "teams": ["McLaren", "Ferrari", "Williams", "Renault"],
        "championships": 4,
        "championship_years": [1985, 1986, 1989, 1993],
        "wins": 51,
        "poles": 33,
        "podiums": 106,
        "fastest_laps": 41,
        "quote": "The Professor",
        "color_primary": "#3498db",
        "color_secondary": "#1a5276",
        "accent": "#2980b9",
        "unlock_bets": 180,
        "tier": "legend",
        "bg_style": "linear-gradient(145deg, #3498db 0%, #1a5276 100%)",
    },
    {
        "id": "senna",
        "name": "Ayrton Senna",
        "full_name": "Ayrton Senna da Silva",
        "nationality": "Brazil",
        "flag": "🇧🇷",
        "era": "1984–1994",
        "teams": ["McLaren", "Toleman", "Lotus", "Williams"],
        "championships": 3,
        "championship_years": [1988, 1990, 1991],
        "wins": 41,
        "poles": 65,
        "podiums": 80,
        "fastest_laps": 19,
        "quote": "And suddenly I realised that I was no longer driving the car consciously, I was driving it by a kind of instinct.",
        "color_primary": "#c0392b",
        "color_secondary": "#7b241c",
        "accent": "#f1c40f",
        "unlock_bets": 350,
        "tier": "myth",
        "bg_style": "linear-gradient(145deg, #c0392b 0%, #7b241c 100%)",
    },
    {
        "id": "schumacher",
        "name": "Michael Schumacher",
        "full_name": "Michael Schumacher",
        "nationality": "Germany",
        "flag": "🇩🇪",
        "era": "1991–2012",
        "teams": ["Ferrari", "Mercedes", "Benetton", "Jordan"],
        "championships": 7,
        "championship_years": [1994, 1995, 2000, 2001, 2002, 2003, 2004],
        "wins": 91,
        "poles": 68,
        "podiums": 155,
        "fastest_laps": 77,
        "quote": "Once something is a passion, the motivation is there.",
        "color_primary": "#c0392b",
        "color_secondary": "#922b21",
        "accent": "#f8c300",
        "unlock_bets": 600,
        "tier": "myth",
        "bg_style": "linear-gradient(145deg, #c0392b 0%, #922b21 100%)",
    },
    {
        "id": "fangio",
        "name": "Juan Manuel Fangio",
        "full_name": "Juan Manuel Fangio",
        "nationality": "Argentina",
        "flag": "🇦🇷",
        "era": "1950–1958",
        "teams": ["Alfa Romeo", "Maserati", "Mercedes", "Ferrari"],
        "championships": 5,
        "championship_years": [1951, 1954, 1955, 1956, 1957],
        "wins": 24,
        "poles": 29,
        "podiums": 35,
        "fastest_laps": 23,
        "quote": "El Maestro — The record that may never be broken.",
        "color_primary": "#2c3e50",
        "color_secondary": "#1a252f",
        "accent": "#d4a843",
        "unlock_bets": 1000,
        "tier": "myth",
        "bg_style": "linear-gradient(145deg, #2c3e50 0%, #1a252f 100%)",
    },
]


def get_legend(legend_id: str) -> dict | None:
    """Return a legend by id, or None if not found."""
    for legend in LEGENDS:
        if legend["id"] == legend_id:
            return legend
    return None
